accounts:
- generic:
    baseUrl: "base_url"
    path: "path"
    pageParameter: "page_parameter"
    perPageParameter: "per_page_parameter"
    pageSize: 20
    selector: "selector"
- generic:
    baseUrl: "base_url"
    path: "path"
    pageParameter: "page_parameter"
    perPageParameter: "per_page_parameter"
    pageSize: 20
    selector: "selector"
    basic:
      username: "username"
      password: "password"
- gitlab:
    baseUrl: "base_url"
    strategy: "HTTP"
    private:
      token: "token"
- gitlab:
    baseUrl: "base_url"
    strategy: "HTTP"
    oauth:
      token: "token"
- github:
    baseUrl: "base_url"
    uploadUrl: "upload_url"
    organizations:
    - org1
    users:
    - user1
    strategy: "HTTP"
- github:
    baseUrl: "base_url"
    uploadUrl: "upload_url"
    organizations:
    - org1
    users:
    - user1
    strategy: "HTTP"
    oauth2:
      token: "token"
      tokenType: "token_type"
      refreshToken: "refresh_token"
      expiry: "expiry"
- bitbucket:
    teams:
    - team1
    users:
    - user1
    strategy: "HTTP"
    basic:
      username: "username"
      password: "password"
- bitbucket:
    teams:
    - team1
    users:
    - user1
    strategy: "HTTP"
    oauth:
      token: "token"
      applicationId: "application_id"
- static:
    repositoryUrls:
    - "repository_urls"
- rds:
    target: "target"
